server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 570528415798-hbkv3j8rhueeve0doa641k8bmrf2ge32.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/InstaVitaliy
    username: postgres
    password: 198855
jwt:
  secret-key: a3ce34220d37d8665c6a3f0698407ed6f57bd3960a6d932416dde5d4a125e550
  token-prefix: Bearer
  header-string: Authorization
  content-type: application/json
  expiration-time: 600_000_000
logging:
  level:
    org:
      springframework:
        security: DEBUG
